# Default as of Sep 2017
dist: trusty

language: php

php:
  - "5.6"
  # Symfony 3.3.8 component/libraries etc. do not like PHP 7.0
  # - "7.0"
  - "7.1"
  - hhvm

env:

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_script:

